import { day1 } from "./day1";
import { day2 } from "./day2";
import { day3 } from "./day3";
import { day4 } from "./day4";
import { day5 } from "./day5";
import { day6 } from "./day6";
import { day7 } from "./day7";

day1();
console.log();
day2();
console.log();
day3();
console.log();
day4();
console.log();
day5();
console.log();
day6();
console.log();
day7();
