import { day1 } from "./day1";
import { day2 } from "./day2";
import { day3 } from "./day3";
import { day4 } from "./day4";
import { day5 } from "./day5";
import { day6 } from "./day6";
import { day7 } from "./day7";
import { day8 } from "./day8";
import { day9 } from "./day9";
import { day10 } from "./day10";
import { day11 } from "./day11";
import { day12 } from "./day12";

day1();
console.log();
day2();
console.log();
day3();
console.log();
day4();
console.log();
day5();
console.log();
day6();
console.log();
day7();
console.log();
day8();
console.log();
day9();
console.log();
day10();
console.log();
day11();
console.log();
day12();
